### ISSUE TITLE
Sending messages with strange characters results in 400 MESSAGE_EMPTY

### ISSUE THREAD

**Issue by ghost** [telegram-s/telegram-api-old#11]
When I try to send messages with characters like these: ñ è é à ç
I get an error: 400, MESSAGE_EMPTY

**Comment by ex3ndr** [comment]
Force your execution and compilation encoding to UTF-8.

**Comment by ghost** [comment]
Thank you! I didn't know this.
If other people have the same problem and are wondering how exactly to do this in eclipse:
1. Right click your project
2. Choose properties
3. On the first page you see change 'Text file encoding' to 'Other: UTF-8'
4. Apply, Ok and it's done!
