### ISSUE TITLE
Does this project even compile?

### ISSUE THREAD

**Issue by SireInsectus** [telegram-s/telegram-api-old#3]
I'm looking at **com.cosmicpush.telegram.AbsApiState** and it has a reference to **org.telegram.api.TLConfig** but that package, let alone class, doesn't even exist.

Am I missing something?

**Comment by ex3ndr** [comment]
com.cosmicpush.telegram.AbsApiState? This project is backed by CI-Server (http://ci.telegram-s.org/), so it mostly always compile.

**Comment by SireInsectus** [comment]
I think I figured out the problem. The distribution does not include the library tl-api-v11.jar

**Comment by ex3ndr** [comment]
Yes, you might link api level that you want.
