### ISSUE TITLE
Any chance we could get a quick start?

### ISSUE THREAD

**Issue by SireInsectus** [telegram-s/telegram-api-old#4]
There is tons of documentation, and I appreciate that, but it is a bit overwhelming. Any chance you could help with a quick start that would get us to the point of sending a simple message? Here is what I have so far...

```
public class Test {

  public static void main(String...args) {
    try {
      new Test().run();
    } catch (Exception e) {
      e.printStackTrace();
    }
    System.exit(0);
  }

  public Test() {
  }

  public void run() throws Exception {

    CpAppInfo appInfo = new CpAppInfo(
      0,                // appId
      "deviceModel",    // device model
      "systemVersion",  // systemv ersion
      "appVersion",     // app version
      "langCode"        // language code.
    );

    TelegramApi api = new TelegramApi(new CpApiState(), appInfo, new ApiCallback() {
      @Override
      public void onApiDies(TelegramApi api) {
        // When auth key or user authorization dies
      }
      @Override
      public void onUpdatesInvalidated(TelegramApi api) {
        // When api engine expects that update sequence might be broken
      }
    });

    TLConfig config = api.doRpcCall(new TLRequestHelpGetConfig());
  }
}
```

**Comment by SireInsectus** [comment]
And I guess I left out of that, sample implementations of **AbsApiState**, **AppInfo** and **Authorizer**

**Comment by SireInsectus** [comment]
If you can help me get started, I would be more than willing to contribute "samples" back in both code and documentation. Having them will help expedite adoption of your APIs.

**Comment by AurelioB** [comment]
I agree, a demo would really help.
I tried following the app's implementation of telegram-api without success.

**Comment by ex3ndr** [comment]
I'll try to create samples and provide some useful tips as fast as i can. For now i am working on Telegram S application.

**Comment by SireInsectus** [comment]
I would be more than happy to help here if you can help us figure out why
we cannot register for an api_id... My only alternative would be to use the
api_id from Telegram S.

-/\/---------/\/\
//\/\UNCHIE-//\/\ONSTER.com
_Jacob_-_D_-_Parr_--|--559-640-7277
General-Manager-/-Owner
www.MunchieMonster.com http://www.munchiemonster.com/

**Comment by SireInsectus** [comment]
Any chance of solving everyone's problem of getting an api_id so that we can help you with this?

**Comment by ex3ndr** [comment]
We are trying to implement updated app_id registration mechanism. For the first time you are able to use app ids that you may find in some our apps at GitHub.

**Comment by SireInsectus** [comment]
We appreciate that very much! We didn't want to use those other IDs without
your blessing.

-/\/---------/\/\
//\/\UNCHIE-//\/\ONSTER.com
_Jacob_-_D_-_Parr_--|--559-640-7277
General-Manager-/-Owner
www.MunchieMonster.com http://www.munchiemonster.com/

On Tue, Mar 11, 2014 at 10:18 AM, Stepan Korshakov <notifications@github.com

**Comment by SireInsectus** [comment]
This is the beauty of open source project... A project specifically for telegram-api samples:

https://github.com/SireInsectus/telegram-api-samples

**Comment by contecavour65** [comment]
Excuse me, i'm new on Eclipse and Java language.
How can i to do:

To get started create a single working folder (ie "telegram"). Then clone into that folder each of the following projects::

telegram-api - same name
telegram-mt - rename the folder "mtproto"
telegram-tl-core - rename the folder "tl-core"
telegram-api-samples - same name
There are some minor build issues in how Gradle is configured that might cause some people problems in the core projects. Until those changes are merged into the main branch, please feel free to use my forks of the following projects:

SireInsectus/telegram-api
SireInsectus/telegram-mt
SireInsectus/telegram-tl-core

Thanks

**Comment by coronapankaj** [comment]
@contecavour65  can you get any solution above all are android studio project they will not import in eclipse

**Comment by contecavour65** [comment]
There is some example to use all in eclipse?
I'd llike to try to send message from a PC.
HAve you some working example code?
Thanks

**Comment by contecavour65** [comment]
@coronapankaj  If i install Android Studio and follw guidelines all works?
I must intall Gradle  in AndroidStudio?

Thanks
