### ISSUE TITLE
Are there any plans to publish to a maven repo?

### ISSUE THREAD

**Issue by SireInsectus** [telegram-s/telegram-api-old#5]
If so, when?

**Comment by ex3ndr** [comment]
I have maven repo, but i stopped using this. May be some day i'll restore my maven repo.

**Comment by SireInsectus** [comment]
We are setting ourselves up to use SonaType to push our artifacts to MavenCentral. I would be more than happy to help out here (in that published maven artifacts make my job just a little easier).

**Comment by ex3ndr** [comment]
We don't want to push artifacts to public maven repo (such as SonaType), because NSA may replace libraries on that servers. So we sometime create our custom maven repo.

**Comment by SireInsectus** [comment]
I don't know that I would have been concerned with that possibility, but
given the nature of your project, that makes sense.

Any chance of getting the registration server back online?

-/\/---------/\/\
//\/\UNCHIE-//\/\ONSTER.com
_Jacob_-_D_-_Parr_--|--559-640-7277
General-Manager-/-Owner
www.MunchieMonster.com http://www.munchiemonster.com/
