### ISSUE TITLE
Ubuntu problem (Linux)

### ISSUE THREAD

**Issue by dmasoft** [telegram-s/telegram-api-old#9]
I think there is a problem with the JVM in linux. When I make a to any method of the API (TLRequestHelpGetConfig for example) I always get a timeOutException. But when I Try it on windows or mac, I get te correct answer. Does anyone know if there is any differences between de JVM??

**Comment by ex3ndr** [comment]
Api is tested for work on Mac OSX. But someone reported that he has timeouts. We need to collect more information.
But, api is not designed for non-unix systems and have never tested in windows.

**Comment by dmasoft** [comment]
I had tested on Windows and it works right. The problem is in linux (Ubuntu). Always returns a timeOutExceptions.

**Comment by Thus0** [comment]
I also had timeout for the telegram-bot (I've only tested on linux/gentoo so far with jvm 1.6.0_45) so perhaps it's a duplicate bug of this one : https://github.com/ex3ndr/telegram-bot/issues/2

**Comment by floens** [comment]
I've been researching the TimeoutException bug for a while now. It appears only on Linux (Debian tested), and not on Windows/mac/freebsd.
I ran Wireshark on Windows and Linux to look for differences, and it looks like that on Linux the packages don't get send to the server after the initial connection. Wireshark shows packages getting send to the server, but on Linux it just... stops.
And after a while it gives a TimeoutException.
So I guess it's a jvm/linux bug.

**Comment by Thus0** [comment]
thanks Floens for your feedback.

I've enabled logging to see where the timeout occurred. I need to look at the mt protocol to get more informations I think :)

'''
Use test DC? (write test for test servers): Using test servers
TelegramApi#1001:Phase 0 in 1 ms
TelegramApi#1001:Phase 1 in 86 ms
TelegramApi#1001:Timeout Iteration
TelegramApi#1001:Connection iteration
TelegramApi#1001:#1: waitForDc
TelegramApi#1001:#1: Creating proto for dc
TelegramApi#1001:#1: Creating key
TelegramApi#1001:Phase 2 in 3 ms
TelegramApi#1001:Sender iteration
api#1001#Downloader:DownloadFileThread iteration
api#1001#Downloader:DownloadFileThread iteration
api#1001#Downloader:DownloadFileThread iteration
api#1001#Downloader:DownloadFileThread iteration
api#1001#Uploader:UploadFileThread iteration
TelegramApi#1001:Phase 3 in 4 ms
api#1001#Uploader:UploadFileThread iteration
Loading fresh DC list...
api#1001#Uploader:UploadFileThread iteration
api#1001#Uploader:UploadFileThread iteration
TelegramApi#1001:Timeout Iteration
TelegramApi#1001:Sender iteration
TelegramApi#1001:>> #0: help.getConfig#c4f9186b
TransportRate:Transport: #1 173.240.5.253:443 #1.0
TransportRate:tryConnection #1
TransportRate:onConnectionSuccess #1
TransportRate:Transport: #1 173.240.5.253:443 #1.0
Authorizer:Solved PQ in 45 ms
TelegramApi#1001:Timeout Iteration
TelegramApi#1001:RPC #0: Timeout (14999 ms)
TelegramApi#1001:Timeout Iteration
org.telegram.api.engine.TimeoutException
completed.
'''

**Comment by dmasoft** [comment]
Well, The only new thing that I have discovered is that the API works in Solaris too. 
I give up about the problem in the debian distribution. I think is a problem related with the JVM or the network configuration. I'm sure that will be fixed in next releases

**Comment by Thus0** [comment]
I've tried Oracle 1.7 or sun 1.6 but same timeout issue

**Comment by floens** [comment]
This seems to fix it:
http://www.virtualzone.de/2011/10/javas-securerandomgenerateseed-on-linux.html

```
java -Djava.security.egd=file:/dev/./urandom -jar foo.jar
```

It's because java by default uses /dev/random which blocks.

**Comment by dmasoft** [comment]
You are right Floens, this solves the problem!!
Thanks!

**Comment by Thus0** [comment]
thanks for the fix :+1: 

I had to change /etc/java-6-openjdk/security/java.security and modify this line 

securerandom.source=file:/dev/./urandom

**Comment by ashokcoolguys** [comment]
I m getting timeout while rpccall for importing contacts, in windows 64bit , jdk 1.7.

**Comment by cancerian0684** [comment]
It started working for me after I updated Server IP Address in the MemoryStateAPI class, as shown below -

``` java
 public void start(boolean isTest) {
        connections = new HashMap<>();
        connections.put(1, new ConnectionInfo[]{
                new ConnectionInfo(1, 0, isTest ? "149.154.175.10" : "149.154.175.50", 443)
        });
    }
```

**Comment by Raakh** [comment]
Can you please send me compiled working code to my email ghayel@gmail.com? I shall be grateful to you

**Comment by dcd99** [comment]
Hi all,
have you finally found a solution to this problem?
could you be so kind to share a complete working code ?
Many thanks in advance for the support.

**Comment by vaibhavthapliyal** [comment]
Hi, I am facing this same issue when sending the auth.checkPhone request. However while sending the auth.sendCode request I was able to solve this problem by adding the java parameters as Floens mentioned. Anybody knows what's happening?

I am using CentOs 6.5 with eclipse luna and java 8

**Comment by floens** [comment]
@vaibhavthapliyal 

> It's because java by default uses /dev/random which blocks.

**Comment by vaibhavthapliyal** [comment]
Hi,

Thanks for the reply. But as I mentioned, I have already applied the runtime parameters that you have suggested and because of that the auth.sendCode was successfully made. But this new request auth.checkphone seems to fail with a TimedOutException.

Thanks
Vaibhav

**Comment by floens** [comment]
Ah. Well try to see with the debugger where the thread hangs (pause the jvm). This library is _very_ old so you might want to look for another telegram solution.

**Comment by vaibhavthapliyal** [comment]
It seems that this is the only JAVA API library for working with the telegram API. I have recompiled this to work with Layer 18 API and was able to run the sendCode request. Were you able to get this done when you were working on it? Is there any other library that you found helpful?

**Comment by amalagaura** [comment]
This answer explains the issue if it is not related to /random

http://stackoverflow.com/a/33941544/234125

**Comment by vaibhavthapliyal** [comment]
Thanks for the link. I'm not sure what happened but the error disappeared by itself. Everything is working now.

**Comment by amalagaura** [comment]
I am continuing to have issues with this library. The author has moved on, so it is understandable.

But I stumbled across this library which is recently released: https://github.com/badoualy/kotlogram
